/* Regenerate the abis the sdk and the site use, from the compiled artifacts.
   Run after any change to a contract signature: a hand maintained abi drifts
   silently and the first symptom is a user's transaction reverting.

   Two outputs on purpose. The sdk ships a small surface, because it is a public
   package and every function in it is a promise to keep. The site gets
   everything, because it is deployed together with the contracts and it also
   needs the guardian side to render a paused banner. */
import { readFileSync, writeFileSync } from 'node:fs'

const read = (n) => JSON.parse(readFileSync(`out/${n}.sol/${n}.json`, 'utf8')).abi

const fns = (n, names) => {
  const abi = read(n)
  const picked = abi.filter((x) => x.type === 'function' && (names === null || names.includes(x.name)))
  if (names) {
    const missing = names.filter((name) => !picked.some((x) => x.name === name))
    // A renamed function would otherwise drop out of the sdk in silence, which
    // is exactly the failure this script exists to prevent.
    if (missing.length) throw new Error(`${n} has no ${missing.join(', ')}`)
  }
  return picked
}

const sdk = {
  basketRouter: fns('BasketRouter', [
    'createIndex', 'createAndBuy', 'buy', 'sell',
    'indexCount', 'legsOf', 'inputOf', 'quoteAllowed', 'paused', 'maxNotional',
  ]),
  rebalancer: fns('Rebalancer', [
    'subscribe', 'unsubscribe', 'rebalance', 'shouldRebalance', 'positionOf',
    'acknowledgeCorporateActions',
  ]),
  orders: fns('Orders', ['place', 'cancel', 'execute', 'ready', 'poke', 'get', 'ordersOf']),
  basketCurve: fns('BasketCurve', [
    'buy', 'sell', 'graduate', 'claim', 'quoteBuy', 'quoteSell',
    'balanceOf', 'raised', 'sold', 'graduated', 'threshold', 'vault', 'usdg', 'indexId',
    'CURVE_SUPPLY', 'usdgReserve', 'tokenReserve', 'pool', 'usdgIsToken0', 'LP_BPS', 'LP_FEE', 'creator',
    'collectFees',
  ]),
  basketFactory: fns('BasketFactory', ['launch', 'count', 'curves', 'curveOfIndex', 'all', 'router', 'quote']),
  tokenSwap: fns('TokenSwap', ['swap', 'factory']),
  basketVault: fns('BasketVault', [
    'redeem', 'backingOf', 'legs', 'legCount', 'minter', 'graduated',
    'balanceOf', 'totalSupply', 'name', 'symbol', 'decimals',
  ]),
}

/* Emitted as TypeScript, not JSON, for two reasons. Node refuses to import a
   json module from an ESM package without an import attribute, so the json
   version threw ERR_IMPORT_ASSERTION_TYPE_MISSING the first time anybody ran
   `import { basketRouterAbi } from '@motif/sdk'` outside a bundler. And `as
   const` gives viem the literal types it needs to infer arguments and returns
   from the abi rather than widening everything to string. */
writeFileSync(
  'packages/sdk/src/abi.generated.ts',
  `/* GENERATED by scripts/gen-abi.mjs. Do not edit: run \`npm run abi\`. */

export const generated = ${JSON.stringify(sdk, null, 2)} as const
`,
)

/* Functions and events, because the site reads both.
   It used to be functions only, and the symptom was as bad as this script
   exists to prevent: `parseEventLogs` matching a `Launched` event against an
   abi that contained no events at all returned nothing, every time, so a launch
   that had actually been mined reported "the transaction carried no Launched
   log" and the creator never got the link to the token they had just paid to
   create. Errors are here for the same reason: without them viem reports a
   revert as an unnamed 4 byte selector. */
const all = (n) => read(n).filter((x) => ['function', 'event', 'error'].includes(x.type))

/* The events the site actually decodes, asserted by name.
   Same reasoning as the sdk's function list above: an event this file stops
   emitting is a page that silently reads nothing, and the last time that
   happened the failure surfaced as a successful launch reporting itself as a
   failure. Cheap to check, and it fails here rather than in a wallet. */
const NEEDED_EVENTS = {
  BasketFactory: ['Launched'],
  BasketRouter: ['IndexCreated', 'Bought', 'Sold'],
  BasketCurve: ['Bought', 'Sold', 'Graduated'],
  BasketVault: ['Redeemed'],
  Orders: ['Placed', 'Cancelled', 'Filled'],
  Rebalancer: ['Subscribed', 'Unsubscribed', 'Rebalanced'],
}

const web = {
  _generated: 'scripts/gen-abi.mjs. Do not edit by hand.',
  BasketRouter: all('BasketRouter'),
  Rebalancer: all('Rebalancer'),
  Orders: all('Orders'),
  BasketCurve: all('BasketCurve'),
  BasketVault: all('BasketVault'),
  BasketFactory: all('BasketFactory'),
  TokenSwap: all('TokenSwap'),
}
for (const [contract, names] of Object.entries(NEEDED_EVENTS)) {
  const have = new Set(web[contract].filter((x) => x.type === 'event').map((x) => x.name))
  const missing = names.filter((n) => !have.has(n))
  if (missing.length) throw new Error(`${contract} has no event ${missing.join(', ')}`)
}

writeFileSync('web/lib/abi.json', `${JSON.stringify(web, null, 2)}\n`)

const webItems = Object.entries(web).filter(([, v]) => Array.isArray(v)).flatMap(([, v]) => v)
const count = (t) => webItems.filter((x) => x.type === t).length
// Named per kind, so a regeneration that silently drops every event again is a
// number that changed rather than a total that still looks about right.
console.log(
  `abis regenerated: sdk ${Object.values(sdk).flat().length} fns, ` +
    `web ${count('function')} fns, ${count('event')} events, ${count('error')} errors`,
)
